version: "3.9"
services:
  app:
    image: nginx:alpine
    container_name: epub-image-checker
    restart: always
    volumes:
      - ./ssh_V1.0:/usr/share/nginx/html:ro
    networks:
      - web

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: